sudo: required

language: java

jdk:
- openjdk8

services:
- docker

cache:
  directories:
  - $HOME/.m2

env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "nFOLJL56A3ZDJZHi0Rf62KzGc941G4Z4WrnASSF2V4ah8RyI4iYuFG6BuFrbn1H0a39BSbjESLSmMp8rROArHnNyuFI56zxnnkW9s8Y4c7eXzh1+YknAPOvr++9tfy/UTGYQ3hdJTIRi1A/ElVGbH8eePB9R3QIJsWaXrMP+v+2b7PHQvB42Ed7vnnqGsNgA348+sbJMlH39PDayBl4DcalycYBIHHd+KdUNj2jGGL0T5M17+UDWV6sm+rM2XhhNy5kVuq6zxLzFFEu1k4NoUYVvjH7xJLkKv7TY5tbWAi172IBzAy63V6e45nrxxTQgGzycsXKKMaUH+eoPjS0WBm/L28jmkYeASKbBpdeaOWGCuOE9fFzT+JzOZNt1xYXFysz2ja/4FxPVpximMgSDcNRKHrh3DfuS0C0h9H5lknVtnoJw0cdXgGs5NziGOlFTSvQBb/r0IiwDKhyJaL7HqhWk7qw6sD+lCZNfcFRr7Z/S+MjQqn388aFLH6NLGAGBXQkIQej/xdpefxFJcS4eYmX+QtqkrY5DsHLjbKSjspFsNkIUgHuWM7OK2TktuEj/pe/iu6WqBC0W0iTyg9fGywtfo4/wlQ/YxQLKmb16MGLQWDTFMw7Umf+AILZfwyde4U/Q5AAvec1UoyJEd+/3X7nMkLKMbIpQ//qj7W4oyMk="
  # AWS_SECRET_ACCESS_KEY
  - secure: "UXbeV0yd4t3+Nqela12vZtSyfuN8MooZ3CTpFYhi0xMlmtmSFgw21loJbuhr9bF1A1G7ckHuDFlRxUu59pd6wLsjX5hn/WK+5K8RB5gMI/IMUxOaU/wucPObXKKnnoHfL73Onbu3fPcodz1ZhwMcviyAI+sVTjDVg+eZZ/lHRcGSdHTltLde2mU8TCBAHCO0GHLzNCur6B9IXAr+dVobSUcInJ7lgRt2J8+ZEpirm0Sd91ENS7LBKQOkwn1nZcMrbvSAOXjFFpEUFeC7Cbsqdl/MvI2NtRJ8vuz3u9E2/WYH7X7se5EQrwm3X/Na8yuGtW9tAKJur0NMXwgYdLsfvntb+crM2TOmdwDM6Sqe6FwfeSncjbpN3kC9eEPOctC4cCnNsCbPHVezBC05eI8lJUn7AP8stAx2+qWIxQrrYParxTG6OuS66IkB0woBe7aOtQY/sTaGN2qzm+nbDVwOFYcJ0wkiZ0XH2gILWeeEPd8aTCfixg4G1nMncuNk48JVIZ5TWiaxPpQka8RhmGZhJ30qceGQx0XOr1DvwYo1kgj1TPMXoI4Ygeq0z/jiv1UFES0nx3hNqCJah0/1/jUhow4D7/lTVJF/FQV+f6a2DvlkjjVUuYJS/kkgWSvix4e+lBv32PAO45r5z+Up/mXoXC1ZXuzOj/4EOZWFeTUx3rY="
  # ARTIFACTORY_USERNAME
  - secure: "PBnTAPgwAdbKePo1heXaoTP+YBzGE6zzdWnsOfo9aSd66XMecuDcRuWvDwDth/ixtP69TanoI8f/37P+q/fhMRlhZ5feTcHnyIDtB3fqvnV36vYcUcPqGiY/QM2lrqMGiItmzRSV6XrLS1mx0Ynq4LW/nEnsg0KlTABlOzgZalKSABHXt++5wuDQiAizOtnSYKsT0lTiLI17T7G0aE4T4tPwPfc2LhOHDMLJtz12buO29W4yi5T2ovSWa+kcSYQgzYeg8s3C6i6MGNqRe+3HIZnzl8cEjeTEBLschO/JodAB4d81oM4bKGT6qm17inJWt7ioS1Oicaf2vIkwK95KHfRKtGSwLwSW2VkWQ4xhqlBkr8CcoO16ZK/KT/N0obPe6tmkY7WYB95gfkycAo2dA/K7mERqe78TmkBofCmv340IoK/k1Rum9BD/x/v2hlEIl+mmzUpt0MS8ZV45nSjZGiEE6/odoE3yKNRdyVqO7D2YGR6eF3MmcPikauXv8meNrSHQIbuhYhHrfcgxfUAFup9dBC2vpLT8MpVb8Z1KesPOI/pIhCEWSBpspC0ZMPHI0nI9eK50+/uduhHIODj/bCCdXoCHTQ5Gmpc15mfRoGSQfVeLGSuaDXzEL2XYK8w0NKuJzHdI4/1MHNsTq+7VBDcq1uhui4ppSdIshjF8X38="
  # ARTIFACTORY_PASSWORD
  - secure: "RMnuZ44ZLFOaupPW8uSjF1OquyokrssPOCSVMBbMDOhQJhxQhASu38fBfHM7191uZaFMdQ3+7E8Q3N50kViph2rMgLFjlTcCqfRy5YD0+Ne1RhCHnwMEwPn0pwrzDgFLsU4dVHDhIOMMDFvRm6Iv3sGprFgtY/uTeNARvuKmj0rejZTVwAX4/cexTd0lE3B2dYOnsmjuQ5sEOWP5wLqaDgbvj8zrRNbcjKz1OiLkf5mBSnTAv3HXSbOkmPE8qT2dR0bjMSf525XM74koIbpSswyouifgIQrmjzAw863uiNWbSQTvmz+letXL4ACbXAF37wJVv+GIWQRoTe/W+wR3R0pv0u4qEdL/dyIR6q/nIvpBVfABBfBAoH9Ds3o77XEjHGuaPgNHnTfHfxyxPuKMu+EGU0JT1+BSkmNswaAU6DlUhZMkv5qspOodE8rg6fF6b/p6V5lNe9L3Rs6eWo6V5mkQouejpfwWEQWgrGp251KNfeywTpEmUUm/zCPpjlmvbi2HG0OjDNN+cbx6kNKq7O3j1zXgAImuAMsYSJQrp+esGRUk3sPruIMP40FlhFXoD6YzBXM6f1q4CYytvPGMnVLl9vkHoXhmqIMz3nUzQbMCJJW8yjJySJYfAZjC77/R8zcAXlKRCyCXAQtYgvz9KzoqR3fVmVOiITb+kHW9yDg="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- export ARTIFACT_NAME="viestintapalvelu"

script:
- mvn clean package -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

- mv -v ryhmasahkoposti-service/target/ryhmasahkoposti-service.war $DOCKER_BUILD_DIR/artifact/ryhmasahkoposti-service.war
- mv -v viestintapalvelu-ui/target/viestintapalvelu-ui.war $DOCKER_BUILD_DIR/artifact/viestintapalvelu-ui.war
- mv -v viestintapalvelu-service/target/viestintapalvelu.war $DOCKER_BUILD_DIR/artifact/viestintapalvelu.war
- cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

- export BASE_IMAGE="baseimage-war-openjdk8:master"
- ./ci-tools/common/pull-image.sh
- ./ci-tools/build/build-war.sh $ARTIFACT_NAME

deploy:
- provider: script
  script: mvn deploy -pl viestintapalvelu-api -DskipTests --settings ci-tools/common/maven-settings.xml
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: mvn deploy -pl ryhmasahkoposti-api -DskipTests --settings ci-tools/common/maven-settings.xml
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true
