name: Viestintäpalvelu

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-  

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Helsinki"

      - name: Build with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn clean install -B -Dbranch=${GITHUB_REF_NAME} -Drevision=${GITHUB_SHA} -DbuildNumber=${GITHUB_RUN_NUMBER}

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            target
            ryhmasahkoposti-api/target
            ryhmasahkoposti-service/target
            viestintapalvelu-api/target
            viestintapalvelu-service/target
            viestintapalvelu-ui/target
          key: ${{ github.sha }}

  deploy-container:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            target
            ryhmasahkoposti-api/target
            ryhmasahkoposti-service/target
            viestintapalvelu-api/target
            viestintapalvelu-service/target
            viestintapalvelu-ui/target
          key: ${{ github.sha }}

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build and deploy Docker container
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          export ARTIFACT_NAME="viestintapalvelu"
          mv -v ryhmasahkoposti-service/target/ryhmasahkoposti-service.war $DOCKER_BUILD_DIR/artifact/ryhmasahkoposti-service.war
          mv -v viestintapalvelu-ui/target/viestintapalvelu-ui.war $DOCKER_BUILD_DIR/artifact/viestintapalvelu-ui.war
          mv -v viestintapalvelu-service/target/viestintapalvelu.war $DOCKER_BUILD_DIR/artifact/viestintapalvelu.war
          cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/
          export BASE_IMAGE="baseimage-war-openjdk8:master"
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-war.sh $ARTIFACT_NAME
          ./ci-tools/github-build/upload-image.sh $ARTIFACT_NAME

  deploy-jar-library:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: |
            target
            ryhmasahkoposti-api/target
            ryhmasahkoposti-service/target
            viestintapalvelu-api/target
            viestintapalvelu-service/target
            viestintapalvelu-ui/target
          key: ${{ github.sha }}

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Deploy jar library
        if: github.ref == 'refs/heads/github-actions'
        shell: bash
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          mvn deploy -B -pl fi.vm.sade.viestintapalvelu:viestintapalvelu,viestintapalvelu-api,ryhmasahkoposti-api -DskipTests --settings ci-tools/common/maven-settings.xml